.\" man page for ATAidle
.\" Contact bruce@cran.org.uk to correct errors or omissions
.TH man 1 "02 January 2004" "0.02" "ATAidle"
.SH NAME
ataidle \- a utility to spindown ata drives after a period of inactivity
.SH SYNOPSIS
.\" Syntax goes here. 
.BR ataidle [-h] -S <idle_mins> <channel> <device>
.SH EXAMPLES
.B SYNOPSIS
.SH DESCRIPTION
.B ATAidle
.SH OPTIONS
.SH FILES
.P 
.SH SEE ALSO
.BR man (1), 
.BR man (7),
.BR apropos (1),
.BR less (1),
.BR groff (1), 
.BR catman (8)
.SH BUGS
Probably lots 
.SH AUTHOR
.nf
Bruce Cran (bruce@cran.org.uk)
.fi
.SH HISTORY

